### ISSUE TITLE
Sliders (on line 238) issue

### ISSUE THREAD

**Issue by N0n3-github** [more-suo/samhain#1]
Slider image stays on the screen if scrolling fast (both, up to down and down to up). Happens not everytime, but frequently.

**Comment by more-suo** [comment]
What slider exactly?

**Comment by N0n3-github** [comment]
In the middle of total height. Where 2 silders are side by side and animate on scroll
--
Отправлено из Mail.ru для Android пятница, 04 сентября 2020г., 22:20 +05:00 от akbar  notifications@github.com :

**Comment by N0n3-github** [comment]
Dunno bro) Two times by accident it occured and disapperaed. I was pretty sure that I caught a bug. But that's ok I think :-)
--
Отправлено из Mail.ru для Android суббота, 05 сентября 2020г., 03:17 +05:00 от akbar  notifications@github.com :

**Comment by more-suo** [comment]
Try to reload the page. It's probably just a issue because the styles are pretty heavy.
